# sig/seedbank/runner.rbs
module Seedbank
  class Runner
    def initialize: (?database_banks: DatabaseBanks) -> void
    def after: (*untyped dependencies) { () -> untyped } -> void
             | (*untyped dependencies) -> void
    def let: (String | Symbol name) { () -> untyped } -> Symbol
    def let!: (String | Symbol name) { () -> untyped } -> untyped
    def evaluate: (untyped seed_task, String seed_file) -> untyped
  end
end
